default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: job_market_monitor_development

test:
  <<: *default
  database: job_market_monitor_test

production:
  <<: *default
  database: job_market_monitor_production
